name: Manage Issue Request
on:
  issues:
    types: [opened, edited]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: manuelht/action-issue2post@master
        with:
          branch: "master" # default to master
          dir: "_requestIntegrationData" # default to _posts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          created_at: ${{ github.event.issue.created_at }}
          title: ${{ github.event.issue.title }}
          body: ${{ github.event.issue.body }}
          actor: ${{ github.actor }}
