name: On Push Show Changes
on: push
jobs:
  pruebas:
    name: Pruebas run git diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - run: |
         git diff --name-status master