name: On Push Run
on: push
jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
      - name: run_script
        uses: actions/checkout@v2
        run: python pruebas.py
        shell: sh