
name: On Pull Request Validate
on:
  pull_request:
    branches:    
      - 'master'
jobs:
  validate-actions:
    name: Validate content
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: '0'
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: |
          pip install -r requirements.txt
          files=$(git diff --name-status origin/master..origin/${{ github.head_ref }})
          python postSync.py ${files}