
name: On Pull Request Validate
on:
  pull_request:
    branches:    
      - 'master'
jobs:
  check-actions:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: |
          pip install -r requirements.txt
          python validate_properties.py properties/test-pipeline.properties